apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  {{ include "application.fullname" . }}.properties: |-
{{- if .Values.configmap.spring }}
{{ tpl .Values.configmap.spring . | nindent 4 }}
{{- end }}
{{- if .Values.configmap.logging }}
{{ tpl .Values.configmap.logging . | nindent 4 }}
{{- end }}
{{- if .Values.configmap.extraConfiguration }}
{{ tpl .Values.configmap.extraConfiguration . | nindent 4 }}
{{- end }}

