apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: {{ if .Values.network.ssl.enabled }}https{{ else }}http{{ end }}
              containerPort: {{ include "application.deployment.port" . }}
              protocol: TCP
            - name: debug-port
              containerPort: 5005
              protocol: TCP
          env:
            {{- if .Values.route.path }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.route.path | quote }}
            {{- end }}
            {{- if .Values.network.ssl.enabled }}
            - name: SERVER_SSL_PEM_KEY
              value: "/etc/k5/security/servicecert/tls.key"
            - name: SERVER_SSL_PEM_CRT
              value: "/etc/k5/security/servicecert/tls.crt"
            {{- end }}
            - name: HOST
              value: {{ required "network.host must be provided" .Values.network.host | quote }}
            - name: APPLICATION_NAME
              value: {{ include "application.fullname" . | quote }}
            {{- with .Values.javaOptions }}
            - name: JAVA_OPTIONS
              value: {{ join " " . | quote }}
            {{- end }}
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- if and .Values.bindings .Values.bindings.datasource .Values.bindings.datasource.url }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.bindings.datasource.url | quote }}
            {{- end }}
            {{- if and .Values.bindings .Values.bindings.datasource .Values.bindings.datasource.username }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.bindings.datasource.username | quote }}
            {{- end }}
            {{- if .Values.bindings }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}-secrets
                  key: datasource-password
                  optional: true
            {{- end }}
            {{- /* MongoDB Configuration */}}
            {{- if and .Values.bindings .Values.bindings.mongodb .Values.bindings.mongodb.uri }}
            - name: SPRING_DATA_MONGODB_URI
              value: {{ .Values.bindings.mongodb.uri | quote }}
            {{- end }}
            {{- if and .Values.bindings .Values.bindings.mongodb .Values.bindings.mongodb.database }}
            - name: SPRING_DATA_MONGODB_DATABASE
              value: {{ .Values.bindings.mongodb.database | quote }}
            {{- end }}
            {{- /* Kafka Configuration */}}
            {{- if and .Values.bindings .Values.bindings.kafka .Values.bindings.kafka.bootstrapServers }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.bindings.kafka.bootstrapServers | quote }}
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KAFKA_SASL_MECHANISM
              value: {{ default "SCRAM-SHA-512" .Values.bindings.kafka.saslMechanism | quote }}
            {{- if .Values.bindings.kafka.secretName }}
            - name: KAFKA_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bindings.kafka.secretName }}
                  key: sasl.jaas.config
                  optional: true
            {{- else if and .Values.bindings.kafka.saslUsername .Values.bindings.kafka.saslPassword }}
            - name: KAFKA_SASL_JAAS_CONFIG
              value: {{ printf "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";" .Values.bindings.kafka.saslUsername .Values.bindings.kafka.saslPassword | quote }}
            {{- end }}
            - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: ""
            {{- if .Values.bindings.kafka.consumerGroupId }}
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: {{ .Values.bindings.kafka.consumerGroupId | quote }}
            {{- end }}
            {{- end }}
            - name: OAUTH2_ISSUER_URI
              value: {{ .Values.bindings.oauth2.issuerUri | quote }}
            {{- if and .Values.bindings .Values.bindings.oauth2 .Values.bindings.oauth2.clientId }}
            - name: OAUTH2_CLIENT_ID
              value: {{ .Values.bindings.oauth2.clientId | quote }}
            {{- end }}
            {{- if and .Values.bindings .Values.bindings.oauth2 .Values.bindings.oauth2.tokenUri }}
            - name: OAUTH2_TOKEN_URI
              value: {{ .Values.bindings.oauth2.tokenUri | quote }}
            {{- end }}
            {{- if .Values.bindings }}
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}-secrets
                  key: oauth2-client-secret
                  optional: true
            {{- end }}
          {{- if .Values.envFromSecrets }}
          envFrom:
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ .name | quote }}
            {{- end }}
          {{- end }}
          startupProbe:
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            httpGet:
              path: {{ include "application.contextPath" . }}/actuator/health
              port: {{ include "application.deployment.port" . }}
              scheme: {{ include "application.deployment.httpScheme" . }}
          readinessProbe:
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: {{ include "application.contextPath" . }}/actuator/health/readiness
              port: {{ include "application.deployment.port" . }}
              scheme: {{ include "application.deployment.httpScheme" . }}
          livenessProbe:
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: {{ include "application.contextPath" . }}/actuator/health/liveness
              port: {{ include "application.deployment.port" . }}
              scheme: {{ include "application.deployment.httpScheme" . }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            {{- if .Values.network.ssl.enabled }}
            - name: servicecert
              mountPath: /etc/k5/security/servicecert
            - name: truststore
              mountPath: /etc/k5/security/truststore
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "application.fullname" . }}-config
        {{- if .Values.network.ssl.enabled }}
        - name: servicecert
          secret:
            secretName: {{ include "application.service-cert.name" . }}
        - name: truststore
          secret:
            secretName: {{ include "application.platform.trustStoreSecret" . }}
        {{- end }}

