{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
{{- end }}

