{{- if .Values.route.enabled -}}
{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "application.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
    {{- with .Values.route.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "application.fullname" . | quote }}
    weight: 100
  {{- if .Values.network.ssl.enabled }}
  port:
    targetPort: https
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- if .Values.route.tls.certificate }}
    certificate: {{ .Values.route.tls.certificate | quote }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: {{ .Values.route.tls.key | quote }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: {{ .Values.route.tls.caCertificate | quote }}
    {{- end }}
  {{- end }}
  {{- else }}
  port:
    targetPort: http
  {{- end }}
{{- end }}
{{- end }}

