apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "application.annotations" . | nindent 4 }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.bindings .Values.bindings.datasource .Values.bindings.datasource.password }}
  datasource-password: {{ .Values.bindings.datasource.password | b64enc }}
  {{- else }}
  datasource-password: {{ "" | b64enc }}
  {{- end }}
  {{- if and .Values.bindings .Values.bindings.oauth2 .Values.bindings.oauth2.clientSecret }}
  oauth2-client-secret: {{ .Values.bindings.oauth2.clientSecret | b64enc }}
  {{- else }}
  oauth2-client-secret: {{ "" | b64enc }}
  {{- end }}
