apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.network.ssl.enabled }}
    {{- if include "application.platform.isOpenshift" . | trim | eq "true" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ include "application.service-cert.name" . | quote }}
    {{- end }}
    {{- end }}
    {{- include "application.annotations" . | nindent 4 }}
  labels:
    service: {{ include "application.fullname" . | quote }}
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.network.ssl.enabled }}
    - name: https
      port: 443
      targetPort: 8443
    {{- else }}
    - name: http
      port: 80
      targetPort: 8080
    {{- end }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
{{- if .Values.network.ssl.enabled }}
{{- if include "application.platform.isOpenshift" . | trim | eq "false" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-tls-internal" (include "application.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  commonName: {{ include "application.fullname" . | quote }}
  dnsNames:
    - {{ include "application.fullname" . }}.{{ .Release.Namespace }}.svc
  secretName: {{ include "application.service-cert.name" . | quote }}
  issuerRef:
    name: {{ required "A valid .Values.services.certification.selfSigned.issuerName" .Values.services.certification.selfSigned.issuerName }}
{{- end }}
{{- end }}
