openapi: 3.0.0
info:
  title: Gift Card API
  version: 1.0.0
  contact: {}
servers:
  - url: https://local.host/giftcard/api/v1
paths:
  /giftcards/{giftCardId}/balance:
    get:
      tags: []
      summary: Get gift card balance
      operationId: GetGiftcardBalance
      parameters:
        - name: giftCardId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
      responses:
        '200':
          description: Giftcard balance successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GiftcardBalance'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/GiftCardNotFound'
  /giftcards/{giftCardId}/transactions:
    get:
      tags: []
      summary: Get gift card payment transactions
      operationId: GetGiftcardsTransactions
      parameters:
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
        - $ref: '#/components/parameters/GiftCardId'
      responses:
        '200':
          description: Transactions for Giftcard successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/GiftCardNotFound'
  /giftcards/{customerId}/giftcards:
    get:
      tags: []
      summary: Get giftcards for customer
      operationId: GetGiftcardsForCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
      responses:
        '200':
          description: Giftcards successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giftcards'
        '400':
          $ref: '#/components/responses/ErrorResponse'
  /giftcards/{giftCardId}/redeem:
    post:
      tags: []
      summary: Redeem gift card at checkout
      operationId: RedeemGiftcard
      parameters:
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
        - $ref: '#/components/parameters/GiftCardId'
      requestBody:
        description: To process redemption necessary request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemFromGiftcard'
      responses:
        '200':
          description: >-
            The gift card has been successfully redeemed with the desired
            amount.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GiftcardBalance'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/GiftCardNotFound'
  /giftcards:
    post:
      tags: []
      summary: Create a new gift card
      operationId: CreateGiftcard
      parameters:
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
      requestBody:
        description: For creating gift card necessary request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGiftcard'
      responses:
        '201':
          description: Gift card successfully created / activated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Giftcard'
        '400':
          $ref: '#/components/responses/ErrorResponse'
  /giftcards/{giftCardId}/refund:
    post:
      tags: []
      summary: 'Refund giftcard '
      description: Operation refunds amount which was before redeemed.
      operationId: refundGiftcard
      parameters:
        - $ref: '#/components/parameters/GiftCardId'
        - $ref: '#/components/parameters/Accept-Language'
        - $ref: '#/components/parameters/X-B3-ParentSpanId'
        - $ref: '#/components/parameters/X-B3-SpanId'
        - $ref: '#/components/parameters/X-B3-TraceId'
        - $ref: '#/components/parameters/X-B3-Sampled'
        - $ref: '#/components/parameters/X-DEBUG-SESSION'
      requestBody:
        description: For refund necessary request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefundToGiftcard'
      responses:
        '200':
          description: Giftcard refund successfully processed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GiftcardBalance'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/GiftCardNotFound'
components:
  parameters:
    Accept-Language:
      name: Accept-Language
      in: header
      description: List of acceptable human languages for response. According to `RFC 7231`
      required: false
      schema:
        type: string
    X-B3-ParentSpanId:
      name: X-B3-ParentSpanId
      in: header
      description: Zipkin Parent Span Id (e.g. `6adc7f8b31f35e91`)
      required: false
      schema:
        type: string
    X-B3-SpanId:
      name: X-B3-SpanId
      in: header
      description: Zipkin Span Id (e.g. `0a7b5cd9c2568f7d`)
      required: false
      schema:
        type: string
    X-B3-TraceId:
      name: X-B3-TraceId
      in: header
      description: Zipkin Trace Id (e.g. `0a7b5cd9c2568f7d6adc7f8b31f35e91`)
      required: false
      schema:
        type: string
    X-B3-Sampled:
      name: X-B3-Sampled
      in: header
      description: Zipkin Sampled (e.g. `0`)
      required: false
      schema:
        type: string
    X-DEBUG-SESSION:
      name: X-DEBUG-SESSION
      in: header
      description: X-DEBUG-SESSION
      required: false
      schema:
        type: string
    GiftCardId:
      name: giftCardId
      in: path
      required: true
      schema:
        type: string
  requestBodies: {}
  responses:
    GiftCardNotFound:
      description: Gift card not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ErrorResponse:
      description: An error occured; details can be found in the Error schema.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    ErrorDetail:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        location:
          type: string
        message:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        detailMessage:
          type: string
        errorDetails:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
        message:
          type: string
        type:
          type: string
    GiftcardBalance:
      type: object
      required:
        - balance
        - currencyCode
      properties:
        balance:
          type: number
        currencyCode:
          type: string
        giftcardId:
          type: string
    Transaction:
      type: object
      required:
        - transactionId
        - action
        - amount
        - executionTimestamp
      properties:
        transactionId:
          type: string
        action:
          type: string
          enum:
            - PLUS
            - SUBTRACT
            - ACTIVATE
            - EXPIRE
        orderReference:
          type: string
        amount:
          type: number
        executionTimestamp:
          type: string
          format: date-time
    Giftcard:
      type: object
      required:
        - balance
        - currencyCode
      properties:
        balance:
          type: number
        currencyCode:
          type: string
        customerId:
          type: string
        description:
          type: string
        name:
          type: string
        giftcardId:
          type: string
    Giftcards:
      type: array
      items:
        $ref: '#/components/schemas/Giftcard'

    Transactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
    CreateGiftcard:
      type: object
      required:
        - balance
        - currencyCode
        - customerId
      description: For creation of a giftcard required input.
      properties:
        balance:
          type: number
        currencyCode:
          type: string
        customerId:
          type: string
    RedeemFromGiftcard:
      type: object
      required:
        - amount
        - currencyCode
        - orderReference
      properties:
        amount:
          type: number
        currencyCode:
          type: string
        orderReference:
          type: string
    RefundToGiftcard:
      type: object
      required:
        - amount
        - currencyCode
        - giftcardId
        - orderReference
      properties:
        amount:
          type: number
        currencyCode:
          type: string
        giftcardId:
          type: string
        orderReference:
          type: string
security: []
tags: []
x-knowis-solutionAcronym: GIFTCARD
x-knowis-apiName: Gift Card API
x-knowis-namespacePrefix: v1
x-knowis-ibmBpmIntegration: false
x-knowis-ibmApiConnectIntegration: false
x-knowis-supportedspec: openApi3.0
x-knowis-apiBasePath: v1